### ISSUE TITLE
Possible Improvements

### ISSUE THREAD

**Issue by BrianComics** [cheesemaafia/scammingthescammers#2]
I noticed your project and I really appreciate it! I have some possible improvements you can make to the code, though. First, there is a module called Faker that allows you to generate fake phone numbers, usernames, and passwords. This offers more variety. For example, some phone numbers start with a 6 or other numbers while your program is hardcoded to start with 9. If you prefer to generate passwords yourself, though, I recommend you replace `for i in range(n): string += str(random.randint(0, 9))` with `string += str(random.randit(0, (n * 10) - 1))`. It basically does the same thing but more efficiently.

Secondly, Python comes with a module built-in called `threading` that allows you to run code simultaneously, boosting your program's speed tremendously.

**Comment by cheesemaafia** [comment]
Thanks a lot for this feedback @BrianComics 

I could have used Faker to generate usernames but that wouldn't have generated Indian names, it can generate Indian names but then again it does so in the Hindi language, defying the purpose of the script

I hardcoded the number 9 because most of the phone numbers in India start with 9, but I'll make this more customizable

Also, thanks for this recommendation, `string += str(random.randit(0, (n * 10) - 1))` , I'm going to include this is my code and I'll definitely look into the `threading` module :)
